### ISSUE TITLE
Break exceed globalmin & max

### ISSUE THREAD

**Issue by Ariel505** [Ariel505/aChor#12]
Dataset: Bodenrichtwerte_Lueneburg.shp
Field: f_flac (Null)
method: 73
val_range: 100~2,000
default swp cal error in aChor.py:
achor_max_val = max(val['properties'][attr] for val in features)
TypeError: '>' not supported between instances of 'NoneType' and 'int'

display val range: 44~1000

Output:

info:b'Break: 1, Breakvalue: 1500,  Globalmax\r\n'
info:b'Break: 2, Breakvalue: 250,  Globalmin\r\n'
info:b'Break: 3, Breakvalue: 600.0\r\n'
info:b'No segments left in database\r\n'
info:b'Break: 4, Breakvalue: 1050.0\r\n'
info:b'Break: 5, Breakvalue: 425.0\r\n'
info:b'Break: 6, Breakvalue: 1275.0\r\n'
info:b'Break: 7, Breakvalue: 825.0\r\n'
info:b'Break: 8, Breakvalue: 512.5\r\n'
info:b'Break: 9, Breakvalue: 337.5\r\n'
info:b'9 breaks/10 classes generated.\r\n'

**Comment by Ariel505** [comment]
2020-02-28T11:38:58     WARNING    Traceback (most recent call last):
              File "/home/hcuadmin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/aChor/aChor.py", line 327, in 
              self.dlg.comboBox.activated.connect(lambda: self.suggest_sweep(str(path).strip(), str(self.dlg.comboBox.currentText()).strip()))
              File "/home/hcuadmin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/aChor/aChor.py", line 384, in suggest_sweep
              achor_max_val = max(val['properties'][attr] for val in features)
             TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by Ariel505** [comment]
Fixed in May 2020 update.
